In [1]:
import tensorflow.compat.v1 as tf
import numpy as np

In [15]:
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [16]:
five=tf.constant(5)

In [17]:
six=tf.constant(6)

In [18]:
eleven=tf.add(five,six)

In [19]:
thirty=tf.multiply(five,six)

In [20]:
sess=tf.Session()

In [21]:
sess.run(eleven)

11

In [22]:
a=tf.zeros([2,3],dtype=tf.float32,name='zero')
b=tf.ones([3,3],dtype=tf.int32,name='one')
c=tf.random_normal([4,5],mean=4,stddev=0.5,name='normal')
d=tf.random_uniform([3,1],-1,1)


In [24]:
sess.run(d)

array([[-0.617543  ],
       [ 0.18373394],
       [-0.34278417]], dtype=float32)

In [25]:
u=np.array([[1.,2.,3.],
            [4.,5.,6.]])

In [27]:
ut=tf.linalg.transpose(u)

In [28]:
sess.run(ut)

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [29]:
uut=tf.linalg.matmul(u,ut)

In [30]:
sess.run(uut)

array([[14., 32.],
       [32., 77.]])

In [31]:
u2=tf.linalg.matmul(u,ut,transpose_a=True,transpose_b=True)

In [32]:
sess.run(u2)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

In [33]:
u2det=tf.linalg.det(u2)
sess.run(u2det)

0.0

In [34]:
uinv=tf.linalg.inv(tf.ones([3,3]))
onedet=tf.linalg.det(tf.ones([4,4]))
sess.run(onedet)

0.0

In [35]:
identity=tf.eye(4)
sess.run(identity)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [36]:
invid=tf.linalg.inv(identity)
sess.run(invid)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [37]:
w2=tf.Variable(tf.random_uniform([3,4],-1,1),name='nextw')
w2.name

'nextw:0'

In [39]:
init=tf.global_variables_initializer()
sess.run(init)
sess.run(w2)

array([[-0.04434228, -0.19874692, -0.44184923,  0.069736  ],
       [ 0.12373209,  0.05274701,  0.19280338, -0.7355015 ],
       [ 0.02073932,  0.28957748,  0.28778625, -0.85963774]],
      dtype=float32)

In [40]:
x=tf.placeholder(tf.float32,name='x',shape=None)
y=tf.placeholder(tf.float32,name='y',shape=None)
z=x*y

In [41]:
sess.run(z,feed_dict={x:[2,3,4],y:[5,6,7]})

array([10., 18., 28.], dtype=float32)

In [42]:
x2=tf.placeholder(tf.float32,name='x2',shape=[None,3])
W2=tf.Variable(tf.random_uniform([3,4],-1,1),name='W2')
b2=tf.Variable(tf.zeros([4]),name='biase2')
output2=tf.linalg.matmul(x2,W2)+b2

init2=tf.initialize_all_variables()


sess.run(init2)

feed2={x2:np.array([[3,2,1],
                  [1,1,2],
                  [4,5,3],
                  [7,7,9],
                  [1,0,1],
                  [0,0,2]])}

sess.run(output2,feed_dict=feed2)

array([[ -1.814131  ,  -4.0358086 ,  -0.50007844,  -0.87742186],
       [ -1.6807463 ,  -1.9487166 ,   0.9607651 ,  -1.7529516 ],
       [ -5.379133  ,  -7.4667673 ,   0.4154153 ,  -1.5678906 ],
       [ -9.479244  , -12.571796  ,   3.3203464 ,  -7.357987  ],
       [ -0.28142238,  -0.9937513 ,   0.30239892,  -1.3016582 ],
       [ -0.914392  ,  -0.42768812,   1.3620038 ,  -1.9650698 ]],
      dtype=float32)

In [43]:
def my_network(input):
    x=tf.placeholder(tf.float32,name='x',shape=[None,3])
    W=tf.Variable(tf.random_uniform([3,4],-1,1),name='W')
    b=tf.Variable(tf.zeros([4]),name='biase')
    output=tf.linalg.matmul(x,W)+b
    
    init=tf.initialize_all_variables()
    sess.run(init)
    
    return sess.run(output,feed_dict={x:input})

In [44]:
i1=np.array([[3,2,1],
              [1,1,2],
              [4,5,3],
              [7,7,9],
              [1,0,1],
              [0,0,2]])

In [45]:
my_network(i1)

array([[ 2.7566948e+00,  1.7602797e+00, -1.0015080e+00, -2.2787840e+00],
       [-2.9906845e-01,  6.4517426e-01,  8.7222672e-01, -1.2475574e+00],
       [ 3.3154356e+00,  2.7402666e+00, -1.8225462e+00, -4.2895370e+00],
       [ 1.9893262e+00,  4.5083833e+00,  1.6407664e+00, -7.6506119e+00],
       [ 8.8587761e-02,  4.7620058e-01,  8.2589507e-01, -6.4950156e-01],
       [-1.6331220e+00,  3.1347275e-03,  1.7859282e+00, -4.3291616e-01]],
      dtype=float32)

In [46]:
init3=tf.initialize_all_variables()
sess.run(init3)

# Loading data

In [48]:
import pandas as pd

In [49]:
abalone_train = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "Age"])


In [50]:
abalone_train.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.435     0.335   0.110         0.334          0.1355          0.0775   
1   0.585     0.450   0.125         0.874          0.3545          0.2075   
2   0.655     0.510   0.160         1.092          0.3960          0.2825   
3   0.545     0.425   0.125         0.768          0.2940          0.1495   
4   0.545     0.420   0.130         0.879          0.3740          0.1695   

   Shell weight  Age  
0        0.0965    7  
1        0.2250    6  
2        0.3700   14  
3        0.2600   16  
4        0.2300   13

In [51]:
abalone_features = abalone_train.copy()
abalone_labels = abalone_features.pop('Age')


In [52]:
abalone_features

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0      0.435     0.335   0.110        0.3340          0.1355          0.0775   
1      0.585     0.450   0.125        0.8740          0.3545          0.2075   
2      0.655     0.510   0.160        1.0920          0.3960          0.2825   
3      0.545     0.425   0.125        0.7680          0.2940          0.1495   
4      0.545     0.420   0.130        0.8790          0.3740          0.1695   
...      ...       ...     ...           ...             ...             ...   
3315   0.605     0.475   0.180        0.9365          0.3940          0.2190   
3316   0.700     0.525   0.190        1.6015          0.7070          0.3650   
3317   0.530     0.420   0.130        0.8365          0.3745          0.1670   
3318   0.395     0.315   0.105        0.3515          0.1185          0.0910   
3319   0.450     0.355   0.120        0.4120          0.1145          0.0665   

      Shell weight  
0           0.0965  
1           0.2250  
2           0.3700  
3           0.2600  
4           0.2300  
...            ...  
3315        0.2950  
3316        0.4300  
3317        0.2490  
3318        0.1195  
3319        0.1600  

[3320 rows x 7 columns]

In [53]:
abalone_labels

0        7
1        6
2       14
3       16
4       13
        ..
3315    15
3316    10
3317    11
3318    16
3319    19
Name: Age, Length: 3320, dtype: int64

In [54]:
abalone_features = np.array(abalone_features)


In [55]:
abalone_features

array([[0.435 , 0.335 , 0.11  , ..., 0.1355, 0.0775, 0.0965],
       [0.585 , 0.45  , 0.125 , ..., 0.3545, 0.2075, 0.225 ],
       [0.655 , 0.51  , 0.16  , ..., 0.396 , 0.2825, 0.37  ],
       ...,
       [0.53  , 0.42  , 0.13  , ..., 0.3745, 0.167 , 0.249 ],
       [0.395 , 0.315 , 0.105 , ..., 0.1185, 0.091 , 0.1195],
       [0.45  , 0.355 , 0.12  , ..., 0.1145, 0.0665, 0.16  ]])

In [56]:
abalone_features.shape

(3320, 7)

In [74]:
def my_network1(input):
    x=tf.placeholder(tf.float32,name='x',shape=[None,7])
    W=tf.Variable(tf.random_uniform([7,1],-1,1),name='W')
    b=tf.Variable(tf.zeros([1]),name='biase')
    output1=tf.linalg.matmul(x,W)+b
   # output=np.sum(output1-abalone_labels.T,axis=0)
    init=tf.initialize_all_variables()
    sess.run(init)
    
    return sess.run(output1,feed_dict={x:input})

In [75]:
my_network1(abalone_features).shape

(3320, 1)

In [85]:
w=np.random.uniform(size=(7,1))

In [103]:
np.matmul(abalone_features,w)-abalone_labels

array([[ -6.17293963,  -5.17293963, -13.17293963, ..., -10.17293963,
        -15.17293963, -18.17293963],
       [ -5.55345947,  -4.55345947, -12.55345947, ...,  -9.55345947,
        -14.55345947, -17.55345947],
       [ -5.26066952,  -4.26066952, -12.26066952, ...,  -9.26066952,
        -14.26066952, -17.26066952],
       ...,
       [ -5.62608547,  -4.62608547, -12.62608547, ...,  -9.62608547,
        -14.62608547, -17.62608547],
       [ -6.19901926,  -5.19901926, -13.19901926, ..., -10.19901926,
        -15.19901926, -18.19901926],
       [ -6.08134897,  -5.08134897, -13.08134897, ..., -10.08134897,
        -15.08134897, -18.08134897]])

In [99]:
abalone_labels=np.array(abalone_labels)

In [105]:
abalone_labels.reshape(1,-1).T

array([[ 7],
       [ 6],
       [14],
       ...,
       [11],
       [16],
       [19]])