In [ ]:
#!pip install --upgrade tensorflow

In [ ]:
#!pip3 install --upgrade pip

In [60]:
import tensorflow.compat.v1 as tf
import numpy as np

In [61]:
tf.disable_v2_behavior()

In [62]:
five=tf.constant(5)
six=tf.constant(6)
eleven=tf.add(five,six)
thirty=tf.multiply(five,six)


In [63]:
sess=tf.Session()

In [64]:
sess.run(eleven)

11

In [65]:
sess.run(thirty)

30

In [66]:
a=tf.zeros([2,3],dtype=tf.float32,name='zero')
b=tf.ones([3,3],dtype=tf.int32,name='one')
c=tf.random_normal([4,5],stddev=0.5)
d=tf.random_uniform([3,2],-1,1)
e=tf.random_normal([2,3],mean=4,stddev=0.5)

In [67]:
sess.run(e)

array([[4.440245 , 3.9283342, 4.491803 ],
       [4.0104475, 4.4286866, 4.3707056]], dtype=float32)

In [68]:
u=np.array([[2.,3.,4.],
            [5.,6.,7.]])

In [69]:
ut=tf.linalg.transpose(u)

In [70]:
sess.run(ut)

array([[2., 5.],
       [3., 6.],
       [4., 7.]])

In [71]:
uut=tf.linalg.matmul(u,ut)

In [72]:
sess.run(uut)

array([[ 29.,  56.],
       [ 56., 110.]])

In [73]:
uut=tf.linalg.matmul(u,ut,transpose_a=True,transpose_b=True)

In [74]:
sess.run(uut)

array([[29., 36., 43.],
       [36., 45., 54.],
       [43., 54., 65.]])

In [75]:
detuut=tf.linalg.det(uut)

In [76]:
sess.run(detuut)

-6.294964549624617e-14

In [77]:
invuut=tf.linalg.inv(uut)

In [78]:
sess.run(invuut)

array([[-1.42971417e+14,  2.85942833e+14, -1.42971417e+14],
       [ 2.85942833e+14, -5.71885667e+14,  2.85942833e+14],
       [-1.42971417e+14,  2.85942833e+14, -1.42971417e+14]])

In [79]:
i=tf.eye(3,3)

In [80]:
sess.run(i)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [81]:
w=tf.Variable(uut,name='weight')

In [82]:
init=tf.initialize_all_variables()

In [83]:
sess.run(init)

In [84]:
sess.run(w)

array([[29., 36., 43.],
       [36., 45., 54.],
       [43., 54., 65.]])

In [85]:
p=tf.placeholder(tf.float32,name='first',shape=None)
q=4*p


In [86]:
sess.run(q,feed_dict={p:[2,3,4,5]})

array([ 8., 12., 16., 20.], dtype=float32)

In [87]:
p2=tf.placeholder(tf.float32,name='first',shape=None)
q2=tf.placeholder(tf.float32,name='second',shape=None)
r2=p2*q2


In [88]:
sess.run(r2,feed_dict={p2:[3,4,5],q2:[6,7,8]})

array([18., 28., 40.], dtype=float32)

In [89]:

x=tf.placeholder(tf.float32,name='x',shape=[None,3])
W=tf.Variable(tf.random_uniform([3,2],-1,1),name='W')
b=tf.Variable(tf.zeros([2]),name='biases')
output=tf.linalg.matmul(x,W)+b

init_op=tf.initialize_all_variables()

sess=tf.Session()
sess.run(init_op)

feed={x:np.array([[5,6,7],
                  [2,3,4],
                  [1,1,2],
                  [2,1,4]])}

sess.run(output,feed_dict=feed)

array([[-8.359296 , -4.070917 ],
       [-4.3690777, -1.8759284],
       [-1.9573102, -1.3991921],
       [-3.4601634, -3.72084  ]], dtype=float32)

In [90]:
def my_network(input):
    W_1=tf.Variable(tf.random_uniform([784,100],-1,1),name='W1')
    b_1=tf.Variable(tf.zeros([100]),name='biases_1')
    output_1=tf.linalg.matmul(input,W_1)+b_1
    
    W_2=tf.Variable(tf.random_uniform([100,50],-1,1),name='W2')
    b_2=tf.Variable(tf.zeros([50]),name='biases_2')
    output_2=tf.linalg.matmul(output_1,W_2)+b_2
    
    W_3=tf.Variable(tf.random_uniform([50,10],-1,1),name='W3')
    b_3=tf.Variable(tf.zeros([10]),name='biases_3')
    output_3=tf.linalg.matmul(output_2,W_3)+b_3
    
    print('Name of weights:',W_1.name,W_2.name,W_3.name)
    print('Name of biases:',b_1.name,b_2.name,b_3.name)
    
    return output_3

In [91]:
i_1=tf.placeholder(tf.float32,[1000,784],name='i_1')

In [92]:
my_network(i_1)

Name of weights: W1_3:0 W2_3:0 W3_3:0
Name of biases: biases_1_3:0 biases_2_3:0 biases_3_3:0


<tf.Tensor 'add_15:0' shape=(1000, 10) dtype=float32>

In [93]:
i_2=tf.placeholder(tf.float32,[1000,784],name='i_1')

In [94]:
my_network(i_2)

Name of weights: W1_4:0 W2_4:0 W3_4:0
Name of biases: biases_1_4:0 biases_2_4:0 biases_3_4:0


<tf.Tensor 'add_18:0' shape=(1000, 10) dtype=float32>

In [95]:
my_network(i_1)

Name of weights: W1_5:0 W2_5:0 W3_5:0
Name of biases: biases_1_5:0 biases_2_5:0 biases_3_5:0


<tf.Tensor 'add_21:0' shape=(1000, 10) dtype=float32>

In [96]:
o=tf.placeholder(float,[1,2],name='o')


In [97]:
t=tf.linalg.matmul(o,tf.transpose(o))

In [98]:
init=tf.initialize_all_variables()

In [99]:
sess.run(init)

In [100]:
sess.run(t,feed_dict={o:np.array([[5,7]])})

array([[74.]], dtype=float32)

In [101]:
25+49

74

In [102]:
def layer(input,weight_shape,bias_shape):
    weight_init=tf.random_normal_initializer(-1,1)
    bias_init=tf.constant_initializer(value=0)
    W=tf.get_variable('W',weight_shape,initializer=weight_init)
    b=tf.get_variable('b',bias_shape,initializer=bias_init)
    
    return tf.matmul(input,W)+b

In [103]:
def my_network2(input):
    with tf.variable_scope('layer_1'):
        output_1=layer(input,[784,100],[100])
        
    with tf.variable_scope('layer_2'):
        output_2=layer(output_1,[100,50],[50])
        
    with tf.variable_scope('layer_3'):
        output_3=layer(output_2,[50,10],[10])
        
    return output_3
        

In [104]:
#i2_1=tf.placeholder(tf.float32,[1000,784],name='i_1')

In [105]:
#my_network2(i2_1)

# Logistic regression

In [106]:
learning_rate=0.01
training_epochs=1000
batch_size=100
display_step=1

In [107]:
def inference(x):
    init=tf.constant_initializer(value=0)
    W=tf.get_variable('W',[784,10],initializer=init)
    b=tf.get_variable('b',[10],initializer=init)
    output=tf.nn.softmax(tf.matmul(x,W)+b)
    
    return output

In [108]:
def loss(output,y):
    dot_product=y*tf.log(output)
    xentropy=-tf.reduce_sum(dot_product,reduction_indices=1)
    loss=tf.reduce_mean(xentropy)
    
    return loss

In [109]:
def training(cost,global_step):
 #   tf.summary.scalar('cost',cost)
    optimizer=tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
    train_op=optimizer.compute_gradients(cost,global_step)
    return train_op

In [110]:
def evaluate(output,y):
    correct_prediction=tf.equal(tf.argmax(output,1),tf.argmax(y,1))
    accuracy=tf.reduce_mean(tf.cast(correct_prediction,tf.float32))
    return accuracy

In [111]:
with tf.Graph().as_default():
    x=tf.placeholder('float',[None,784])
    y=tf.placeholder('float',[None,10])
    
    output=inference(x)
    cost=loss(output,y)
    global_step=tf.Variable(0,name='global_step',trainable=False)
    train_op=training(cost,global_step)
    eval_op=evaluate(output,y)
    summary_op=tf.summary.merge_all()
    saver=tf.train.Saver()
    sess=tf.Session()
    summary_writer=tf.summary.FileWriter('logistic_logs/',graph_def=sess.graph_def)
    init_op=tf.initialize_all_variables()
    sess.run(init_op)
    
    for epoch in range(training_epochs):
        avg_cost=0.
        total_batch=int(mnist.train.num_examples/batch_size)
        for i in range(total_batch):
            mbatchx, mbatchy=mnist.train.next_batch(batch_size)
            feed_dict={x:mbatchx,y:mbatchy}
            sess.run(train_op,feed_dict=feed_dict)
            minibatch_cost=sess.run(cost,feed_dict=feed_dict)
            avg_cost+=minibatch_cost/total_batch
        if epoch % display_step == 0:
            val_feed_dict={x:mnist.validation.images,
                           y:mnist.validation.labels}
            accuracy=sess.run(eval_op,feed_dict=val_feed_dict)
            print('validation error:',1-accurary)
            summary_str=sess.run(summary_op,feed_dict=feed_dict)
            summary_writer.add_summary(summary_str,sess.run(global_step))
            saver.save(sess,'logistic_logs/model-checkpoint',global_step=global_step)
            
    print('optimization finished')
    
    test_feed_dict={x:mnist.test.images,y:mnist.test.labels}
    
    accuracy=sess.run(eval_op,feed_dict=test_feed_dict)
    
    print('test accuracy',accurary)

NameError: name 'mnist' is not defined