In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
x=tf.Variable(3.0)

with tf.GradientTape() as tape:
    y=x**2
    


In [3]:
dy_dx=tape.gradient(y,x)

In [5]:
dy_dx.numpy()

6.0

In [17]:
w=tf.Variable(tf.random.normal((3,2)),name='w')
b=tf.Variable(tf.zeros(2,tf.float32),name='b')
x=[[1.0, 2.0, 3.0]]

with tf.GradientTape(persistent=True) as tape:
    y=x @ w+b
    loss=tf.reduce_mean(y**2)
    

In [18]:
[dloss_dw, dloss_db]=tape.gradient(loss, [w,b])

In [19]:
my_variables={'w':w,'b':b}
grad=tape.gradient(loss,my_variables)

In [20]:
grad['w']

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ -5.209317 ,  -5.9433346],
       [-10.418634 , -11.886669 ],
       [-15.627952 , -17.830004 ]], dtype=float32)>

In [24]:
layer=tf.keras.layers.Dense(20,activation='relu')
x=tf.constant([[1., 2., 3.]])

with tf.GradientTape(persistent=True) as tape:
    y=layer(x)
    loss=tf.reduce_mean(y**2)
    
grad=tape.gradient(loss,layer.trainable_variables)

In [25]:
grad

[<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
 array([[0.13188525, 0.        , 0.24974942, 0.10492277, 0.08109027,
         0.        , 0.06072878, 0.06901947, 0.1127395 , 0.19193168,
         0.01008061, 0.1083164 , 0.        , 0.04430643, 0.        ,
         0.01360787, 0.13142155, 0.        , 0.06618112, 0.12208553],
        [0.2637705 , 0.        , 0.49949884, 0.20984554, 0.16218054,
         0.        , 0.12145755, 0.13803895, 0.22547899, 0.38386336,
         0.02016121, 0.2166328 , 0.        , 0.08861287, 0.        ,
         0.02721574, 0.2628431 , 0.        , 0.13236223, 0.24417105],
        [0.39565575, 0.        , 0.74924827, 0.3147683 , 0.24327081,
         0.        , 0.18218634, 0.20705843, 0.33821848, 0.57579505,
         0.03024182, 0.3249492 , 0.        , 0.13291931, 0.        ,
         0.04082362, 0.39426464, 0.        , 0.19854334, 0.3662566 ]],
       dtype=float32)>, <tf.Tensor: shape=(20,), dtype=float32, numpy=
 array([0.13188525, 0.        , 0.24974942, 0.1

In [26]:
x=tf.constant(3.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    y=x**2
    
dy_dx=tape.gradient(y,x)

In [27]:
dy_dx.numpy()

6.0

In [31]:
x0=tf.constant(0.0)
x1=tf.constant(10.0)

with tf.GradientTape(persistent=True) as tape:
    
    tape.watch(x1)
    y0=tf.math.sin(x0)
    y1=tf.math.sin(x1)
    
    y=y0+y1
    

In [36]:
g=tape.gradient(y,{'x0':x0,'x1':x1})

In [39]:
g['x0']

In [40]:
g['x1']

<tf.Tensor: shape=(), dtype=float32, numpy=-0.8390715>

In [44]:
x=tf.constant(3.0)

with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    y=x*x
    z=y*y
    

In [45]:
g2=tape.gradient(z,y)

In [46]:
g3=tape.gradient(z,x)

In [47]:
g2.numpy()

18.0

In [48]:
g3.numpy()

108.0

In [49]:
x=tf.Variable(2.0)
with tf.GradientTape(persistent=True) as tape:
    y0=x**2
    y1=1/x
    
    

In [50]:
tape.gradient(y0,x).numpy()

4.0

In [51]:
tape.gradient(y1,x).numpy()

-0.25

In [52]:
x=tf.Variable(2.0)

with tf.GradientTape() as tape:
    y=x*[3., 4.]

In [53]:
tape.gradient(y,x).numpy()

7.0