In [1]:
#!pip3 install --upgrade tensorflow

In [3]:
import tensorflow.compat.v1 as tf
import numpy as np

In [4]:
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [5]:
five=tf.constant(5)

In [7]:
six=tf.constant(6)

In [9]:
eleven=tf.add(five,six)

In [10]:
thirty=tf.multiply(five,six)

In [11]:
sess=tf.Session()

In [12]:
sess.run(eleven)

11

In [13]:
sess.run(thirty)

30

In [32]:
a=tf.zeros([2,3],dtype=tf.float32,name='zero')
b=tf.ones([3,3],dtype=tf.int32,name='one')
c=tf.random_normal([4,5],mean=4,stddev=0.5,name='normal')
d=tf.random_uniform([3,1],-1,1)

In [36]:
sess.run(d)

array([[-0.42837977],
       [ 0.63633823],
       [ 0.8508637 ]], dtype=float32)

uniform distribution pdf in the interval $$[a,b]$$:

$$f(x)=\frac{1}{b-a}$$

In [46]:
u=np.array([[1.,2.,3.],
            [4.,5.,6.]])

In [47]:
ut=tf.linalg.transpose(u)

In [48]:
sess.run(ut)

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [49]:
uut=tf.linalg.matmul(u,ut)

In [50]:
sess.run(uut)

array([[14., 32.],
       [32., 77.]])

In [51]:
u2=tf.linalg.matmul(u,ut,transpose_a=True,transpose_b=True)

In [52]:
sess.run(u2)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

In [53]:
u2det=tf.linalg.det(u2)

In [54]:
sess.run(u2det)

0.0

In [58]:
uinv=tf.linalg.inv(tf.ones([3,3]))

In [61]:
onedet=tf.linalg.det(tf.ones([4,4]))

In [62]:
sess.run(onedet)

0.0

In [63]:
identity=tf.eye(4)

In [64]:
sess.run(identity)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [65]:
invid=tf.linalg.inv(identity)

In [66]:
sess.run(invid)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [72]:
w2=tf.Variable(tf.random_uniform([3,4],-1,1),name='nextw')

In [73]:
w2.name

'nextw:0'

In [74]:
init=tf.initialize_all_variables()

In [75]:
sess.run(init)

In [76]:
sess.run(w2)

array([[ 0.075104  ,  0.89497304, -0.52148414,  0.9587145 ],
       [-0.14901185,  0.82549834, -0.41255474, -0.8515134 ],
       [ 0.66654634, -0.05518913,  0.01936722,  0.35947108]],
      dtype=float32)

y=3*x



In [80]:
x=tf.placeholder(tf.float32,name='x',shape=None)
y=tf.placeholder(tf.float32,name='y',shape=None)
z=x*y

In [81]:
z

<tf.Tensor 'mul_2:0' shape=<unknown> dtype=float32>

In [82]:
sess.run(z,feed_dict={x:[2,3,4],y:[5,6,7]})

array([10., 18., 28.], dtype=float32)

In [92]:
x2=tf.placeholder(tf.float32,name='x2',shape=[None,3])
W2=tf.Variable(tf.random_uniform([3,4],-1,1),name='W2')
b2=tf.Variable(tf.zeros([4]),name='biase2')
output2=tf.linalg.matmul(x2,W2)+b2

init2=tf.initialize_all_variables()


sess.run(init2)

feed2={x2:np.array([[3,2,1],
                  [1,1,2],
                  [4,5,3],
                  [7,7,9],
                  [1,0,1],
                  [0,0,2]])}

sess.run(output2,feed_dict=feed2)

array([[ -1.0004401 ,   0.16499686,  -1.6675808 ,  -1.1308453 ],
       [ -1.1335213 ,   1.4458733 ,  -2.127811  ,  -1.7322841 ],
       [ -4.126482  ,   0.42759824,  -4.980133  ,  -3.5485394 ],
       [ -6.530786  ,   5.356854  , -10.771195  ,  -8.402687  ],
       [  0.14351177,   1.0846574 ,  -0.71074414,  -0.6449187 ],
       [ -0.5615454 ,   1.9057035 ,  -1.6493926 ,  -1.4893208 ]],
      dtype=float32)

In [99]:
def my_network(input):
    x=tf.placeholder(tf.float32,name='x',shape=[None,3])
    W=tf.Variable(tf.random_uniform([3,4],-1,1),name='W')
    b=tf.Variable(tf.zeros([4]),name='biase')
    output=tf.linalg.matmul(x,W)+b
    
    init=tf.initialize_all_variables()
    sess.run(init)
    
    return sess.run(output,feed_dict={x:input})

In [100]:
i1=np.array([[3,2,1],
              [1,1,2],
              [4,5,3],
              [7,7,9],
              [1,0,1],
              [0,0,2]])

In [101]:
my_network(i1)

array([[-1.4189799 , -0.42810726,  0.757869  ,  2.1940322 ],
       [ 1.2285049 , -1.6994498 , -0.30960846,  2.2752516 ],
       [ 0.08655167, -3.1174304 ,  2.4380407 ,  5.747504  ],
       [ 3.6335533 , -7.7208433 ,  0.51432514, 11.934149  ],
       [ 0.09679532, -0.369452  , -0.76818156,  0.8376188 ],
       [ 1.9863925 , -1.6701221 , -1.0726337 ,  1.597045  ]],
      dtype=float32)

In [97]:
init3=tf.initialize_all_variables()


sess.run(init3)

In [98]:
sess.run(my_network(i1))

InvalidArgumentError: You must feed a value for placeholder tensor 'x_8' with dtype float and shape [?,3]
	 [[node x_8 (defined at <ipython-input-93-33ed5161de6c>:2) ]]

Original stack trace for 'x_8':
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 497, in start
    self.io_loop.start()
  File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/lib/python3/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python3/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/lib/python3/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/lib/python3/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2824, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-98-04ef1322d40d>", line 1, in <module>
    sess.run(my_network(i1))
  File "<ipython-input-93-33ed5161de6c>", line 2, in my_network
    x=tf.placeholder(tf.float32,name='x',shape=[None,3])
  File "/home/mehrdad/.local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 3271, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/mehrdad/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6746, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/mehrdad/.local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/mehrdad/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3565, in _create_op_internal
    op_def=op_def)
  File "/home/mehrdad/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
