In [1]:
#!jt -t solarizedl

In [13]:
import numpy as np  

# Sets

In [25]:
empty_set=set()

In [26]:
x={'a','b','c'}

In [28]:
y={'c','d','d','e','f'}

In [29]:
y

{'c', 'd', 'e', 'f'}

In [31]:
x.union(y)

{'a', 'b', 'c', 'd', 'e', 'f'}

In [32]:
x.intersection(y)

{'c'}

In [33]:
x.difference(y)

{'a', 'b'}

In [34]:
'a' in x

True

In [35]:
'a' not in x

False

In [36]:
x.issubset(y)

False

# Vectors

In [21]:
u=np.array([1,2,3])

In [22]:
v=np.array([4,5,6])

In [24]:
np.dot(u,v) 

32

In [48]:
np.linalg.norm(u)

3.7416573867739413

In [50]:
t=np.inner(u,v)/(np.linalg.norm(u)*np.linalg.norm(v))

In [57]:
np.degrees(np.arccos(t))

12.933154491899135

# Matrices

In [3]:
A=np.array([[1,2,3],
            [4,5,6]])

In [4]:
A.shape

(2, 3)

In [5]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
B=np.array([[1,0,1],
           [0,1,0],
           [1,1,1]])

In [8]:
np.dot(A,B).shape

(2, 3)

In [9]:
np.dot(A,B)

array([[ 4,  5,  4],
       [10, 11, 10]])

In [12]:
np.matmul(A,B)

array([[ 4,  5,  4],
       [10, 11, 10]])

In [58]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
Z=np.array([[1,1,0],
            [0,1,1],
            [1,0,1]])

In [67]:
np.linalg.inv(Z)

array([[ 0.5, -0.5,  0.5],
       [ 0.5,  0.5, -0.5],
       [-0.5,  0.5,  0.5]])

In [68]:
np.linalg.det(Z)

2.0

In [72]:
X=np.array([[2,3]])
Y=np.identity(2)

In [73]:
np.kron(X,Y)

array([[2., 0., 3., 0.],
       [0., 2., 0., 3.]])

In [82]:
np.kron(np.identity(3),np.zeros((4,5))+3)

array([[3., 3., 3., 3., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 3., 3., 3., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 3., 3., 3., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 3., 3., 3., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 3., 3., 3., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 3., 3., 3., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 3., 3., 3., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 3., 3., 3., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 3., 3., 3., 3.]])

In [75]:
A=np.array([[0,1,1],
           [1,0,1],
           [1,1,0]])

In [76]:
np.linalg.eigvals(A)

array([-1.,  2., -1.])

In [77]:
np.linalg.eig(A)

(array([-1.,  2., -1.]), array([[-0.81649658,  0.57735027,  0.19219669],
        [ 0.40824829,  0.57735027, -0.7833358 ],
        [ 0.40824829,  0.57735027,  0.59113912]]))

In [83]:
x={1,2,3}
y={'a','b'}
zip(x,y)

In [85]:
[(i,j) for i, j in zip(x,y)]

[(1, 'b'), (2, 'a')]

In [86]:
a=np.array([[0,1,1],
            [1,0,1],
            [1,1,0]])
b=np.array([[3],
            [4],
            [1]])


In [87]:
np.dot(np.linalg.inv(a),b)

array([[1.],
       [0.],
       [3.]])

In [88]:
Z

array([[1, 1, 0],
       [0, 1, 1],
       [1, 0, 1]])

In [89]:
A

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [90]:
np.dot(A,A)

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [91]:
B=np.dot(A,A)

In [92]:
np.linalg.eig(B)

(array([1., 4., 1.]), array([[-0.81649658,  0.57735027,  0.381008  ],
        [ 0.40824829,  0.57735027, -0.81590361],
        [ 0.40824829,  0.57735027,  0.43489561]]))

In [95]:
x=2*np.identity(3)

In [107]:
y=np.ones((4,4))

In [108]:
np.kron(y,x)

array([[2., 0., 0., 2., 0., 0., 2., 0., 0., 2., 0., 0.],
       [0., 2., 0., 0., 2., 0., 0., 2., 0., 0., 2., 0.],
       [0., 0., 2., 0., 0., 2., 0., 0., 2., 0., 0., 2.],
       [2., 0., 0., 2., 0., 0., 2., 0., 0., 2., 0., 0.],
       [0., 2., 0., 0., 2., 0., 0., 2., 0., 0., 2., 0.],
       [0., 0., 2., 0., 0., 2., 0., 0., 2., 0., 0., 2.],
       [2., 0., 0., 2., 0., 0., 2., 0., 0., 2., 0., 0.],
       [0., 2., 0., 0., 2., 0., 0., 2., 0., 0., 2., 0.],
       [0., 0., 2., 0., 0., 2., 0., 0., 2., 0., 0., 2.],
       [2., 0., 0., 2., 0., 0., 2., 0., 0., 2., 0., 0.],
       [0., 2., 0., 0., 2., 0., 0., 2., 0., 0., 2., 0.],
       [0., 0., 2., 0., 0., 2., 0., 0., 2., 0., 0., 2.]])